zowe/zowe-native-proto

- native/c/zowex.cpp
`zowex data-set restore <dsn>` command to restore / recall archived / migrated data sets.
> restore data set command

- doc/apis.md
> Update API matrix

- native/c/zds.cpp
- native/c/zusf.cpp
> fix: enhance encoding check and remove printf

- .github/workflows/zos-build.yml
- tools/build/config.default.jsonc
- tools/build/src/main.ts
Adds a workflow to build native binaries on the Marist z/OS system. Thanks @MarkAckert for helping to set this up 😋 
> Add CI workflow for z/OS build

- README.md
- package-lock.json
- packages/sdk/src/ZSshClient.ts
- packages/sdk/src/ZSshUtils.ts
- packages/vsce/package.json
- packages/vsce/rspack.config.js
- packages/vsce/src/SshConfigUtils.ts
* Fix breakpoints and incremental build not working for SDK package in VS Code debugger ([#55](https://github.com/zowe/zowe-native-proto/issues/55))
* Fix issue found by @jace-roell where SSH profiles with incorrect port may cause deploy to hang
* Fix issue found by @traeok where SSH profiles with empty hostname were shown in quickpick
> Fix deploy bugs and rspack config for vsce

- biome.json
- packages/sdk/src/ZSshClient.ts
- packages/vsce/src/SshClientCache.ts
- packages/vsce/src/api/SshMvsApi.ts
> remove connection from clientMap when connection closes, biome config

- doc/client/architecture.md
> Add vsce to client architecture doc

- doc/apis.md
- native/c/zcn.cpp
- native/c/zds.cpp
- native/c/zdstype.h
- native/c/zjb.cpp
- native/c/zjb.hpp
- native/c/zjbm.c
- native/c/zjbtype.h
- native/c/zowex.cpp
- native/c/zut.cpp
- native/c/zut.hpp
`zowex job list --prefix "name*"`
> Job list by prefix

- README.md
- native/c/ztso.cpp
Restructure project readme to be more comprehensive and make it easier for contributors to get started.
> Restructure project readme

- tools/build/src/main.ts
Properly rejects the promise in runCommandInShell 😋 
Cause an error and run the deploy:build script
```
Deploying files... \
Deploy complete!
Converting files from 'utf8' to 'IBM-1047'... -
Convert complete!
Building native/c ...
Running: cd /u/users/fernando/zowe-native-proto/c && make -
Error: runCommand connection.exec error: 
"./zowex.cpp", line 1426.38: CCN5274 (S) The name lookup for "memers" did not find a declaration.
CCN0793(I) Compilation failed for file ./zowex.cpp.  Object file not created.
FSUM8226 make: Error code 12 
Done!
node:internal/process/promises:389
new UnhandledPromiseRejection(reason);
^
UnhandledPromiseRejection: This error originated either by throwing inside of …
```
> fix: reject the promise if the exit code is different than 0 :yum:

- README.md
- packages/vsce/rspack.config.js
- packages/vsce/tsconfig.json
Also adds tip to the readme about defining `serverPath` for easier testing.
> Update rspack config to hide long warning text

- .github/workflows/zos-build.yml
- native/golang/go.mod
- package.json
- scripts/buildTools.ts
> Fix zos-build workflow hanging

- native/c/zut.cpp
- native/golang/cmds/ds.go
- native/golang/cmds/jobs.go
- native/golang/cmds/uss.go
- native/golang/utils/bytes.go
- native/golang/utils/zos.go
- packages/vsce/src/api/SshMvsApi.ts
- packages/vsce/src/api/SshUssApi.ts
> Fix --encoding option for view commands

- package-lock.json
- packages/cli/src/issue/console/ConsoleCommand.definition.ts
- packages/cli/src/list/data-set-members/DataSetMembers.definition.ts
- packages/cli/src/list/data-set/DataSet.definition.ts
- packages/cli/src/list/jobs/Jobs.definition.ts
- packages/cli/src/list/uss-files/UssFiles.definition.ts
- packages/cli/src/server/install/Install.definition.ts
- packages/cli/src/server/uninstall/Uninstall.definition.ts
- packages/cli/src/upload/file-to-data-set/FileToDataSet.definition.ts
- packages/cli/src/upload/file-to-data-set/FileToDataSet.handler.ts
- packages/cli/src/upload/file-to-uss-file/FileToUssFile.definition.ts
- packages/cli/src/upload/file-to-uss-file/FileToUssFile.handler.ts
- packages/cli/src/view/data-set/DataSet.definition.ts
- packages/sdk/src/ZClientUtils.ts
- packages/sdk/src/ZSshUtils.ts
- packages/vsce/package.json
- packages/vsce/src/SshConfigUtils.ts
- packages/vsce/src/api/SshUssApi.ts
> lint: a few suggestions for resolving the lint issues

- native/CHANGELOG.md
Adds missing changelog entries for changes in #143
> chore: add missing changelog for changes in #143

- native/c/zcli.hpp
- native/c/zowex.cpp
- native/golang/cmds/cmds.go
- native/golang/cmds/dispatcher.go
- native/golang/cmds/ds.go
- native/golang/cmds/jobs.go
- native/golang/cmds/uss.go
- native/golang/main.go
- native/golang/types/common/common.go
- native/golang/utils/stdio.go
Enhances #149 to retrieve exit code from `zowex` commands and return it in JsonRPC response object from I/O server
> Pass zowex return codes through I/O server

- .github/workflows/update-project.yml
> Add workflow to update GitHub project

- packages/vsce/src/SshConfigUtils.ts
> Smart ssh connection cleanup

- native/c/zds.cpp
Fixes a bug I inadvertently caused by trying to be consistent with DD reading in #173 
IBM doc recommends using `fread`, and since we've been using `ifstream` up to this point, it felt like it made sense to switch to the recommended function. 
In addition, this avoids strange behavior from `ifstream` (such as incorrect results from `ifstream::tellg`) and allows us to pass different record formats. It's also a bit faster because we don't seek to the end of the data set to determine its size (which seems to be buggy with `ifstream` anyway)
- Open a standard DS (such as fixed block) and see the same byte-for-byte output as z/OSMF
- Do the same with a PDS member w/ RECFM=U and notice byte-for-byte output is identical
> fix(ds): use fread to prevent newline in binary DS

- packages/vsce/src/SshClientCache.ts
- packages/vsce/src/SshConfigUtils.ts
- packages/vsce/src/api/SshCommandApi.ts
- packages/vsce/src/extension.ts
> fix: Add port to SSH client ID in vsce

- doc/apis.md
- native/CHANGELOG.md
- native/c/zowex.cpp
- native/golang/cmds/definitions.go
- native/golang/cmds/jobs.go
- native/golang/types/jobs/requests.go
- native/golang/types/jobs/responses.go
- packages/cli/CHANGELOG.md
- packages/cli/src/hold/Hold.definition.ts
- packages/cli/src/hold/job/Job.definition.ts
- packages/cli/src/hold/job/Job.handler.ts
- packages/cli/src/release/Release.definition.ts
- packages/cli/src/release/job/Job.definition.ts
- packages/cli/src/release/job/Job.handler.ts
- packages/sdk/CHANGELOG.md
- packages/sdk/src/AbstractRpcClient.ts
- packages/sdk/src/doc/gen/jobs.ts
Adds support for the hold/release operations for jobs
Deploy and run the CLI commands `zowe zssh hold|release job <job-id>`
Just trying to complete the apis.md table as much as possible 😋
> Add support for `hold` and `release` job operations

- packages/sdk/src/ZSshUtils.ts
- packages/vsce/src/SshConfigUtils.ts
- packages/vsce/src/Utilities.ts
- scripts/buildTools.ts
- scripts/watchNative.js
* Fixes Deploy command failing for ssh profile with private key
* Updates profiles in tree immediately after Deploy & Uninstall commands
* Adds build flags to shrink Go binary size w/o affecting stack traces
> fix(client): Fix issues with deploy command

- .gitignore
- README.md
- doc/apis.md
- doc/server/ioserver_architecture.md
- native/c/makefile
- native/c/test.sh
- native/c/zowex.cpp
- native/golang/cmds/cmds.go
- native/golang/cmds/dispatcher.go
- native/golang/cmds/ds.go
- native/golang/cmds/jobs.go
- native/golang/cmds/uss.go
- native/golang/go.mod
- native/golang/main.go
- native/golang/tygo.yaml
- native/golang/types/cmds/requests.go
- native/golang/types/cmds/responses.go
- native/golang/types/ds/requests.go
- native/golang/types/ds/responses.go
- native/golang/types/jobs/requests.go
- native/golang/types/jobs/responses.go
- native/golang/types/uss/requests.go
- native/golang/types/uss/responses.go
- native/golang/utils/cmd.go
- native/golang/utils/log.go
- native/golang/worker.go
- packages/sdk/src/ZSshClient.ts
- packages/sdk/src/ZSshUtils.ts
- scripts/buildTools.ts
Also renames `zowexx` to `zoweax` for Zowe Authorized eXecutable
> chore(native): Rename `ioserver` binary to `zowed`

- packages/sdk/src/ZSshClient.ts
> Fix dangling promise that made commands hang

- .github/release.config.js
- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/zos-build.yml
- package.json
- packages/vsce/package.json
> Add release workflow and run build workflows on push

- .github/release.config.js
- .github/workflows/build.yml
- .github/workflows/release.yml
> Fix issues in release workflow

- packages/sdk/src/ZSshUtils.ts
> Add trace logging to debug ssh connection issues

- .vscode/launch.json
- packages/cli/src/download/Download.definition.ts
- packages/cli/src/download/data-set/DataSet.definition.ts
- packages/cli/src/download/data-set/DataSet.handler.ts
- packages/cli/src/download/job-file/JobFile.definition.ts
- packages/cli/src/download/job-file/JobFile.handler.ts
- packages/cli/src/download/uss-file/UssFile.definition.ts
- packages/cli/src/download/uss-file/UssFile.handler.ts
- packages/cli/src/view/data-set/DataSet.definition.ts
- packages/cli/src/view/job-file/JobFile.definition.ts
- packages/cli/src/view/uss-file/UssFile.definition.ts
Add commands to download data sets, uss files, and spool files
> Add commands to download data sets, uss files, and spool files

- packages/cli/README.md
- packages/cli/src/imperative.ts
- packages/sdk/README.md
- packages/vsce/README.md
Adds READMEs for the VS Code extension, CLI plug-in and SDK
> chore: readmes & CLI plugin first steps

- .github/workflows/release.yml
> fix(release): don't persist credentials at checkout

- .github/release.config.js
- .github/workflows/release.yml
⚠️ Depends on https://github.com/zowe-actions/octorelease/pull/160 being merged
Fixes issue with auto-generation for changelogs not working properly
> Update release config for Octorelease fixes

- packages/cli/src/server/install/Install.handler.ts
- packages/sdk/src/ZSshUtils.ts
- packages/vsce/src/SshConfigUtils.ts
- packages/vsce/src/Utilities.ts
Adds progress for command palette command `Connect to host` and CLI command `zowe zssh server install` via a callback method in the `installServer()` method
> add progress indicator to CLI and VSCE for deploying the server

- .github/workflows/build.yml
- .gitignore
- biome.json
- jest.config.js
- package-lock.json
- package.json
- packages/cli/package.json
- packages/sdk/__mocks__/ssh2.ts
- packages/sdk/__tests__/ZSshClient.test.ts
- packages/sdk/package.json
- packages/sdk/src/ZSshClient.ts
- packages/vsce/package.json
- tsconfig.test.json
> Add unit tests for SSH client class

- .github/workflows/audit.yml
Scans npm deps - there are no Go deps that need to be scanned 😋 
> Add CI workflow for npm audit

- scripts/buildTools.ts
> Fix checksum generation in the build tool

- packages/vsce/src/Utilities.ts
> Open log file in read-only mode in VSCE

- packages/sdk/CHANGELOG.md
- packages/sdk/src/ZSshClient.ts
- packages/sdk/src/ZSshUtils.ts
- packages/sdk/src/doc/client.ts
- packages/sdk/test/ZSshClient.test.ts
- packages/vsce/CHANGELOG.md
- packages/vsce/package.json
- packages/vsce/src/SshClientCache.ts
Fixes #260 
1. Use the VS Code extension to perform an action like listing data sets
2. Put your PC to sleep and wait a few minutes
3. Resume your PC and wait for network connection to be established
4. Notice that VS Code extension is still usable 🙂 
> Add keep-alive messages to keep SSH connection active

- native/c/zds.cpp
- native/c/zds.hpp
- native/c/zowex.cpp
Add `zowex data-set create-loadlib` convenience command 
> create loadlib wrapper

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/zos-build.yml
> Fix checksums.asc not bundled in the vsce

- .github/release.config.js
- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/zos-build.yml
Signed-off-by: Andrew W. Harn <andrew.harn@broadcom.com>
Updates workflows to do the following:
- Perform deployments to Zowe JFrog
- Add PR comment with Server artifacts
- Add PR comment with Client artifacts
> Update release workflow to upload to JFrog

- package-lock.json
- packages/cli/package.json
- scripts/bundleCliTgz.js
> fix: Bundle all dependencies in CLI tgz except cpu-features

- native/CHANGELOG.md
- native/c/makefile
- native/c/zowex.cpp
- scripts/buildTools.ts
> feat: zowex --version, zowex version cmd

- native/CHANGELOG.md
- native/c/zjb.cpp
- native/c/zowex.cpp
> feat: add full_status to rfc output of view status cmd

- .github/workflows/release.yml
- .github/workflows/zos-build.yml
- scripts/buildTools.ts
Fixes #465 
Can't easily test until next time we publish a release - see dry run workflow [here](https://github.com/zowe/zowe-native-proto/actions/runs/16820250380)
> fix(ci): Update version of native build in release workflow

- packages/vsce/CHANGELOG.md
- packages/vsce/src/api/SshCommonApi.ts
Fixes https://github.com/zowe/zowe-native-proto/issues/540
Install a prerelease of ZE 3.3.0 and verify that SSH profiles are usable with both password and private key.
> fix(vsce): Ensure that ISession is defined on node session

- package-lock.json
> Update `tar-fs` transitive dependency for audit
