zowe/zowe-native-proto

native/CHANGELOG.md
native/c/zcli.hpp
native/c/zds.cpp
native/c/zjb.cpp
native/c/zusf.cpp
native/c/zut.cpp

Now that `langlvl(extended0x)` is used for C++ code, we should use `nullptr` instead of `NULL` when assigning default values for pointers.
Build this branch and notice the successful complication. Test the `zowex` binary (using the shell script or a few test commands) to verify behavior is still as expected.

refactor: replace NULL -> nullptr where applicable

---

doc/server/ioserver_architecture.md

Adds the design doc for `ioserver` to `doc/server/ioserver_architecture.md`.

ioserver design doc

---

native/golang/cmdutils.go
native/golang/ds.go
native/golang/issue.go
native/golang/job.go
native/golang/uss.go
packages/sdk/src/ZSshClient.ts

Fixes several limitations related to SSH and ioserver:
* Enables `pty` mode for SSH connection to support `sh`
* Echo is disabled to prevent `stdin` being piped to `stdout`
* Pty mode merges `stdout` and `stderr` into a single stream
* Fixes #9 
* Using `exec` instead of `shell` bypasses user login script
* Fixes #42 
* `ioserver` now invokes `zowex` in the executable directory

Fix ioserver comms over non-Bash shell

---

native/c/zcli.hpp

`zowex job l` for example causes s0c4 abend. this is a quick fix to prevent that and surface an error message instead

prevent s0c4 if verb not found

---

packages/vsce/CHANGELOG.md
packages/vsce/src/api/SshMvsApi.ts
packages/vsce/src/api/SshUssApi.ts

Resolves comment about "Open w/ Encoding: Binary" in #34 

fix: pass binary as encoding value in VSCE

---

.github/workflows/zos-build.yml

Also use `pull_request` trigger which is safer than `push`, and prettify the JSON object.

Configure GOCACHE variable in workflow

---

.github/workflows/build.yml
.gitignore
native/golang/utils/zos.go
native/golang/utils/zos_mock.go
scripts/buildTools.ts

Also restores local `go build` to GitHub workflow since it frequently fails on z/OS system.

Support compiling ioserver off z/OS

---

native/c/zowex.cpp
native/c/zusf.cpp

Using `std::string::append` caused the file path to be mangled as part of remaining recursive calls.

fix(zusf): avoid use of append in recursive logic

---

native/CHANGELOG.md
native/c/makefile
native/c/zcli.cpp
native/c/zcli.hpp
native/c/zds.cpp
native/c/zusf.cpp

- Resolves a few dangling pointers in `zcli.hpp` by avoiding use of `new` & replacing the dereferenced pointers with static instances
- Fixes issue where response contents were appended with random junk data - replaced manual allocation with `vector<char>`
- Open several files in the VSCE. Notice that the data is intact w/o any junk data at the end.

fix: CLI dangling pointers; read resource contents into vector

---

native/c/zds.cpp

Updates the logic to be consistent with how we read from ddnames for jobs.
Doesn't really fix any issues, just wanted to be consistent instead of refactoring the read for data sets - and since we were already using this method, it makes sense to reuse the code we already have.

fix(ds): Use same read process as `zds_read_from_dd` in `zds_read_from_dsn`

---

native/c/makefile

Fixes #178 - now the `zos-build` workflow is failing until the warnings are addressed in b3728f2596f5d0c5d45810cefc8b6567ce67ee2c and caac03033c37126ce30091c0f06e2f6b79704d11 😋 

Fail make build for compiler and linker warnings

---

native/CHANGELOG.md
native/c/zds.cpp
native/c/zds.hpp
native/c/zowex.cpp
packages/cli/CHANGELOG.md
packages/cli/src/list/data-set/DataSet.handler.ts
packages/vsce/CHANGELOG.md
packages/vsce/src/api/SshMvsApi.ts

- Defines max data set length as constant `MAX_DS_LENGTH = 44`
- Replace use of `44` with constant variable where applicable
- Performs length check for data set search pattern before performing list operation
- Appends `.**` to data set search pattern to match z/OSMF behavior
- Open the VSCE, search for `SYS1.*` instead of `SYS1.**` using the build from this branch
- Notice that the results match z/OSMF this time
- Search for another pattern that has a wildcard in its qualifier, e.g.: `TRAE.ENC*`
- Notice that this pattern now matches data sets starting with `TRAE.ENC`

fix(ds/list): Address inconsistent results (compared to z/OSMF) for DS search patterns

---

packages/cli/src/SshBaseHandler.ts
packages/sdk/src/ZSshClient.ts
packages/sdk/src/doc/client.ts
packages/vsce/src/SshClientCache.ts

Adds `onError` callback for improved handling of generic request errors. Now the VS Code extension will show these errors with `vscode.window.showErrorMessage` instead of silently writing them to the console.
Also adds a request timeout of 60 seconds - thanks @traeok for the idea! Hopefully our requests never take this long, but in case we do they shouldn't hang any more.

fix(sdk): Add error callback and request timeout to SSH client

---

native/CHANGELOG.md
native/golang/cmds/ds.go

Fixes an issue where listing data sets with a non-existent pattern causes `zowed` to hang with no response.
- List a data set pattern in the VSCE that doesn't exist on the target system
- Notice "No data sets found" rather than infinitely hanging

fix: No response from `zowed` when listing data sets w/ non-existent pattern 

---

native/CHANGELOG.md
native/golang/cmds/jobs.go
native/golang/utils/cmd.go
native/golang/utils/stdio.go
packages/cli/src/SshBaseHandler.ts
packages/sdk/src/ZSshClient.ts
packages/sdk/src/doc/client.ts

- Removes newline from job IDs as part of output
- Use 1 worker for the CLI plug-in to avoid starting unnecessary workers
- Try to submit a job through the VSCE (right click in editor -> "Submit as JCL") and click the hyperlink
- Use the CLI with a command, notice the successful response.

fix: newline in job ID after submit, use 1 worker for CLI plug-in

---

packages/vsce/src/api/SshJesApi.ts

spotted while testing before release
List jobs with a prefix through the VS Code extension. Notice that results are filtered to only match jobs starting with said prefix.

fix(vsce): pass prefix to request for list jobs

---

native/CHANGELOG.md
native/c/zds.cpp
native/c/zowex.cpp
native/c/zusf.cpp

- Fixes issue where a S0C4 is encountered when invoking `./zowex uss write` or `./zowex ds write` without using the `--etag-only` parameter.
- Writes are still successful, but the exception is something that should be avoided
- Fixes issue where a no-op occurs when the `--encoding` flag is not provided to the USS write or DS write commands (more severe)
- Test the current build on main when doing a USS write or DS write through a SSH shell. Don't pass the `--etag-only` parameter
- Notice the S0C4 and abrupt termination
- Test the build on this branch and notice the S0C4 does not occur when `--etag-only` is not provided

fix: s0c4 if `--etag-only` not specified on writes

---

native/CHANGELOG.md
native/c/zds.cpp
packages/vsce/CHANGELOG.md

Fixes issue where the e-tag did not match the e-tag for the saved contents when a data set was saved with encoding.
- Open a data set in an editor from the VSCE, with either the default encoding (just click on it) or a custom one (right-click -> "Open with Encoding")
- In the same window, make a conflict using `zowex` from a terminal, e.g.:
- `echo "test changes" | ./zowex ds write "TEST.DATASET(MEM1)"`
- Make a change in the data set and try to save it to trigger a conflict
- Notice a conflict is detected and both Overwrite / Compare works as expected

fix(ds): E-tag mismatch when data set saved with encoding specified

---

native/CHANGELOG.md
native/golang/main.go
native/golang/types/common/options.go
native/golang/utils/log.go
native/golang/worker.go
packages/sdk/src/doc/gen/common.ts

- No longer wait for all workers to be available and remove use of WaitGroup
- Asynchronously initializes workers to reduce time-to-input for `zowed` once started by the client
- Allows server to start accepting requests as soon as the first worker is available
- Balances requests in the same fashion as before, but prioritizes available workers in the event that requests are more immediate
- Adds verbose logging to `zowed` for debugging purposes
- Moves request queue into worker pool for more explicit code separation
- Start the server from the VSCE or CLI and notice that the client does not take as long to validate/wait to send input

async init for workers, remove WaitGroup

---

packages/vsce/src/SshConfigUtils.ts
packages/vsce/src/Utilities.ts

Validates keyPassphrases and passwords on existing ssh profiles and prompts for corrections if necessary 
- Create an ssh profile with an incorrect password or keypassphrase and attempt to utilize that ssh profile.
- enter the correct credential when the text input appears.
- Check the config file for a corrected credential, if it was previously in plaintext, it will now be in the secure array assuming isSecure() returns true for your context

validate ssh profiles when used on vsce

---

packages/vsce/src/SshConfigUtils.ts

- Refactor `promptForProfile()` in SshConfigUtils.ts to have logic broken up
- Remove unused methods now that `validateConfig()` handles prompting and returning passwords
- Fix regression in regards to using found private keys within `~/.ssh/config`
- Improved regex validation for a custom/new ssh connection via an ssh command ex `ssh example@user` or `example@user`
**How to test**
**Cases**
1.
- a. Within your ssh config file `(~/.ssh/config)` create a profile that has an `IdentityFile` that is valid for an existing ssh connection with a corresponding `hostname`
Ex:
```
Host Example
HostName Example.net
user TestUser
Port 22
IdentityFile /Users/Test/.ssh/id_test
```
Note: IdentityFile should **NOT** have one of the automatically detected algorithm names - …

vsce: Refactor `promptForProfile()`

---

.github/workflows/release.yml
.github/workflows/zos-build.yml
package.json
scripts/buildTools.ts

Adds `zoweax` binary to the server PAX that we publish to GitHub releases 😋 
Run `npm run z:artifacts:all` and verify that there are 2 different server PAX files generated: one in `dist` with `zoweax` and another in `packages/*/bin` without `zoweax`.

Add zoweax to server PAX release artifact

---

.vscode/settings.json
native/c/zadata.hpp
native/c/zowex.cpp

`zowex tool run <pgm>` did not accept input.  For now, this adds a few options:
```
Options:
--dynalloc-pre,--dp         dynalloc pre run statements
--dynalloc-post,--dt        dynalloc post run statements
--in-dd,--idd               input ddname
--input,--in                input
--out-dd,--odd              input ddname
```
This allows a user to specify files for dynallocation performed before and after the program is run to `alloc` and `free`.  You can also specify an `out-dd` to echo results of a specific dd upon completion as well as provide `--input` on the command line to an `--in-dd`.
Assuming you have `amblist_pre.txt`:
```
alloc dd(syslib) da('dkelosky.loadlib') shr
alloc dd(sysin) 
alloc dd(sysprint) 
```
And `amblist_post.txt`
```
free dd(syslib) 
free dd(sysin) …
```

Add Parms to Run

---

native/c/zadata.hpp
native/c/zds.cpp
native/c/zds.hpp
native/c/zdstype.h
native/c/zowex.cpp
native/c/zusf.cpp
native/c/zusf.hpp
native/c/zusftype.h
native/golang/cmds/ds.go
native/golang/cmds/uss.go

Adds `--return-etag` option to the `zowex ds view` and `zowex uss view` commands. The default value is false. When true it will print the etag.
Updates the `zowex ds write` and `zowex uss write` commands so that they don't print the etag unless `--etag-only` option is specified.
Test the following commands:
* `zowex ds|uss view` with and without `--return-etag` option
* `zowex ds|uss write` with and without `--etag-only` option
* `zowex ds|uss write` with the `--etag` option to test mismatch

Add `--return-etag` flag so displaying etag is optional

---

scripts/watchNative.js

This should make the watch script more reliable 😋 
* Terminate SFTP sessions to avoid hitting max session limit of 10
* Add keep alive interval of 30s to match the ZNP SSH client

Fix watch script exceeding max session limit

---

native/CHANGELOG.md
native/c/extern/zb64.h
native/c/zds.cpp
native/c/zds.hpp
native/c/zowex.cpp
native/golang/cmds/ds.go
native/golang/types/ds/requests.go
packages/sdk/CHANGELOG.md
packages/sdk/src/doc/gen/ds.ts

Kudos to @t1m0thyj for all his work in #311 as without it this wouldn't be possible 🙏 
Let's get to streaming ⏯️ 
Build the artifacts & SDK for this branch (`npm install && npm run build && npm run z:all`), then deploy the actual server using the VSCE or CLI. Then run the following script: `node test.js <localFile> <dsname> <encoding>`
e.g. `node test.js 10mb_local_file.dat "TRAE.TESTDS(MEMB)" binary`
note that the data set or member must exist
```js
const fs = require("fs");
const { ProfileInfo } = require("@zowe/imperative");
const { SshSession } = require("@zowe/zos-uss-for-zowe-sdk");
const { ZSshClient } = require("./packages/sdk");
let client;
async function main(localFile, dsname, encoding) {
const profInfo = new ProfileInfo("zowe");
await …
```

feat: Support streaming for read/write DS

---

.github/workflows/release.yml
package.json
scripts/moveArtifacts.js

Fixes error in the release workflow where downloading second PAX fails because it would overwrite the first one.

Fix artifact download in release workflow

---

native/c/parser.hpp
native/c/zowex.cpp

There was some back and forth on whether we want a `--n` alias for auto-negated flags. For example, if a `--warn` flag is added to a command with default value of `true`, a negated flag is available with following aliases: `--nwarn, --no-warn`
This changes the behavior so only `--no-warn` is available. It establishes consistency with yargs (Zowe CLI command interpreter) and avoids extra logic for the alias checks.
Run `./zowex ds list -h` and see that the "no-warn" option no longer has the `--nwarn` alias

refactor: remove --n alias for "negated flag" generation 

---

native/CHANGELOG.md
native/c/makefile
native/c/test/makefile
native/c/test/ztest.cpp
native/c/test/ztest.hpp
native/c/test/ztest_runner.cpp
native/c/test/zusf.test.cpp
native/c/test/zusf.test.hpp
native/c/zowex.cpp
native/c/zusf.cpp
native/c/zusf.hpp

- Fixes handling cases where `strtol` fails to parse the given mode in the `zusf_chmod_uss_file_or_dir` function. I've removed the `strtol` logic altogether, and the command handler now passes the octal value into the function to save the overhead of converting to string for recursive calls.
- Added support for capturing lambdas so we can declare common variables outside of lambdas for tests 😋 should help with avoiding code duplication and now the callables behave like "arrow functions" (akin to Jest) where you can capture variables outside of the function's scope.
Run the command: `./zowex uss chmod 777 /u/users/<username>/<some_file_here>`
Notice that the command was successful, and the permissions are now accurately set.
I certify …

Support capturing lambdas in `ztest`, fix mode parsing for `zusf_chmod_uss_file_or_dir`

---

README.md
native/c/makefile
package.json
scripts/buildTools.ts

Optimizes the default targets built by `make` to remove `xlclang-extenders` and `tests`.
This should make the `z:build` and `z:rebuild` scripts significantly faster, and fix `z:watch`.
Since `xlclang-extenders` is required to run tests, it has been moved to the `z:test` script.
First clean your environment with `z:delete`, then try the `z:rebuild` and `z:test` commands.

dev: optimize default make target

---

native/CHANGELOG.md
native/c/zusf.cpp
packages/cli/src/download/uss-file/UssFile.handler.ts
packages/cli/src/upload/file-to-uss/FileToUss.handler.ts
packages/cli/src/view/uss-file/UssFile.handler.ts

Fixes regression from #421 that caused hanging when testing `zowe zssh uss download` command in #358.
For files tagged as UTF-8 (ccsid 1208), we were attempting to convert UTF-8 -> UTF-8 which does not behave well.
Also fixes the order of precedence for codepage checks to match z/OSMF.
Verify that the CLI commands for uploading/downloading USS files respect codepage if specified as an argument.

fix(uss): Prioritize user-specified encoding over file tag when reading/writing USS files

---

native/c/zbase64.h
native/c/zds.cpp
native/c/zusf.cpp
package-lock.json

fix: Refactor base64 encoding to handle leftover bytes correctly

---

native/c/test/makefile
native/c/zrecovery.h

When building tests, I introduced a link/bind-time warning for symbol `ZRCVYARR`.  This makes the function `static`.  We also remove the `clean` from the default `make` target in tests.

Fix Link Warning

---

packages/sdk/CHANGELOG.md
packages/sdk/src/AbstractConfigManager.ts

Fixes #453
On MacOS, run the "Connect to Host" command and deploy to a system that uses private key.

fix: Prevent unnecessary keyring prompts when using private key

---

native/CHANGELOG.md
native/c/lexer.hpp

Fixed issue where the "at symbol" (`@`) and the pound sign `#` were not correctly interpreted as identifiers
- `ds restore TEST.#NC@DED` makes it to the actual restore operation (ofc it will fail because the data set doesn't exist)

refactor(lexer): support all characters as part of an identifier

---

native/CHANGELOG.md
native/c/zowex.cpp
scripts/buildTools.ts

Fixes #498
Run `./zowex ds lm SYS1.MACLIB --me 1 --no-warn` and verify that the return code is 0.

Fix zowex --no-warn ends with rc != 0

---

native/CHANGELOG.md
native/c/zowex.cpp

Prevents duplicate submission in `zowex job submit-jcl` command
- Deploy and build
- `printf "//IEFBR14$ JOB (IZUACCT),TEST,REGION=0M\n//RUN EXEC PGM=IEFBR14" | zowex job submit-jcl`
- Notice only one job is created from running this. You'll see 2 jobs when running based off of `main`

fix: duplicate submit in submit-jcl handler

---

native/CHANGELOG.md
native/c/zds.cpp

- Removes re-assignment of `rc` by assigning RC of `ZDSDSCB1` to new local-scoped var
- List my HLQ on one of the prod servers (ping me internally if you need my user)
- Succeeds on this branch, fails on main

fix(ds/list): error when listing if OBTAIN fails

---

native/c/test/makefile

These changes should reduce the size of the `c/test/build-out` folder by a few hundred MB 😋 
* Disables generation of `.lst` files unless DEBUG flag is set
* Creates symlinks to `.o` files instead of copying them

Reduce size of build-out folder generated for tests

---

packages/sdk/src/ZSshUtils.ts

- Fixes an issue from #533 where the Retry button did not invoke `installServer` when server deployment fails OR `uninstallServer` when server uninstall fails
Here's what I do to fill up a volume/dir to run out of free space:
- run `df -m ~` to see how much free space is left in your home dir
- then run `dd if=/dev/zero of=/your/home/dir/large_file.dat bs=1024576 count=X` where `X` is the number of available megabytes returned from `df -m ~`
_Install:_
- Deploy to a volume or directory where you don't have any free space; see the friendly error
- Make some free space and select "Retry"
- See that deployment succeeds and same progress bar is reused 😋 
_Uninstall:_
- Uninstall from a volume or directory where you don't have permission to delete; see the …

fix: Retry button should invoke `installServer/uninstallServer` again
